virtiofsd-obj-y = buffer.o \
                  fuse_opt.o \
                  fuse_loop_mt.o \
                  fuse_lowlevel.o \
                  fuse_signals.o \
                  fuse_virtio.o \
                  helper.o \
                  passthrough_ll.o

