common-obj-y += block.o cdrom.o hd-geometry.o
common-obj-$(CONFIG_PFLASH_CFI01) += pflash_cfi01.o


obj-$(CONFIG_VIRTIO) += virtio-blk.o
obj-$(CONFIG_VIRTIO) += dataplane/
ifeq ($(CONFIG_VIRTIO),y)
obj-$(CONFIG_VHOST_USER_BLK) += vhost-user-blk.o
endif
