#ifndef HW_ACPI_REDUCED_H
#define HW_ACPI_REDUCED_H

#define ACPI_REDUCED_SLEEP_LEVEL	  5
#define ACPI_REDUCED_SLEEP_ENABLE	  (1<<5) /* SLP_EN */
#define ACPI_REDUCED_SLEEP_CONTROL_IOPORT 0x3B0
#define ACPI_REDUCED_SLEEP_STATUS_IOPORT 0x3D0
#define ACPI_REDUCED_RESET_IOPORT	  0x3C0
#define ACPI_REDUCED_RESET_VALUE	  4
#define ACPI_REDUCED_PMTIMER_IOPORT   0x3E0

void acpi_reduced_setup(MachineState *machine, AcpiConfiguration *conf);

#endif
