# shared objects
obj-y += ppc.o ppc_booke.o fdt.o
# IBM pSeries (sPAPR)
# IBM PowerNV
ifeq ($(CONFIG_PCI)$(CONFIG_PSERIES)$(CONFIG_LINUX), yyy)
obj-y += spapr_pci_vfio.o
endif
# PowerPC 4xx boards
obj-y += ppc4xx_devs.o ppc405_uc.o
# PReP
obj-${CONFIG_RS6000_MC} += rs6000_mc.o
# OldWorld PowerMac
# NewWorld PowerMac
# e500
# PowerPC 440 Xilinx ML507 reference board.
