common-obj-y += pam.o

# PPC devices
# NewWorld PowerMac
# PowerPC E500 boards

# ARM devices

common-obj-$(CONFIG_PCI_PIIX) += piix.o
common-obj-$(CONFIG_PCI_Q35) += q35.o
common-obj-$(CONFIG_PCI_GENERIC) += gpex.o

