obj-$(CONFIG_PCI) += pci.o

ifeq ($(CONFIG_VFIO_PCI_QUIRKS_IGD), y)
obj-y += pci-igd.o
else
obj-y += pci-igd-stub.o
endif

ifeq ($(CONFIG_VFIO_PCI_QUIRKS_ATI), y)
obj-y += pci-ati.o
else
obj-y += pci-ati-stub.o
endif

ifeq ($(CONFIG_VFIO_PCI_QUIRKS_NVIDIA), y)
obj-y += pci-nvidia.o
else
obj-y += pci-nvidia-stub.o
endif
