ifeq ($(CONFIG_LINUX), y)
devices-dirs-$(CONFIG_SOFTMMU) += quirks/
obj-y += quirks/
obj-$(CONFIG_SOFTMMU) += common.o
obj-$(CONFIG_PCI) += pci.o
obj-$(CONFIG_VFIO_VGA) += display.o
obj-$(CONFIG_VFIO_CCW) += ccw.o
obj-$(CONFIG_SOFTMMU) += platform.o
obj-$(CONFIG_VFIO_XGMAC) += calxeda-xgmac.o
obj-$(CONFIG_VFIO_AMD_XGBE) += amd-xgbe.o
obj-$(CONFIG_SOFTMMU) += spapr.o
endif

obj-$(call lnot,$(CONFIG_VFIO_VGA))  += stub.o
