common-obj-$(CONFIG_ARM_TIMER) += arm_timer.o
common-obj-$(CONFIG_ARM_MPTIMER) += arm_mptimer.o
common-obj-$(CONFIG_ARM_V7M) += armv7m_systick.o
common-obj-$(call land, $(CONFIG_PIIX),$(CONFIG_I8254)) += i8254_common.o i8254.o
ifeq ($(CONFIG_ISA_BUS),y)
endif
common-obj-$(CONFIG_PL031) += pl031.o


obj-$(CONFIG_MC146818RTC) += mc146818rtc.o



