common-obj-y += hid.o
common-obj-$(CONFIG_PCKBD) += pckbd.o
common-obj-y += ps2.o

common-obj-$(CONFIG_VIRTIO) += virtio-input.o
common-obj-$(CONFIG_VIRTIO) += virtio-input-hid.o
ifeq ($(CONFIG_LINUX),y)
common-obj-$(CONFIG_VIRTIO) += virtio-input-host.o
endif

