common-obj-$(CONFIG_DS1225Y) += ds1225y.o
common-obj-$(CONFIG_I2C) += eeprom_at24c.o
common-obj-y += fw_cfg.o
common-obj-$(CONFIG_CHRP_NVRAM) += chrp_nvram.o
common-obj-$(CONFIG_MAC_NVRAM) += mac_nvram.o
obj-$(CONFIG_PSERIES) += spapr_nvram.o

common-obj-$(call lor,$(CONFIG_EEPRO100_PCI),$(CONFIG_ESP_PCI)) += eeprom93xx.o
